### ISSUE TITLE
How to receive various images in a HTML?

### ISSUE THREAD

**Issue by dinamiqo** [unsplash/unsplash-source-js#10]
I have a FOR and inside him  the call to URL to your API for put a image like a cover from a post in my blog, but when I render in the browser, I obtain the same image in all post. How to I change this? 

![screenshot_1](https://cloud.githubusercontent.com/assets/7528423/17687200/c3f3464c-6338-11e6-8f85-b743b4af0322.png)

**Comment by dechuck** [comment]
Hey @dinamiqo 

You can have a look to this issue( #9 ) for more information about this browser feature.

Thanks

**Comment by dinamiqo** [comment]
Thanks, friend! :smile:

**Comment by dechuck** [comment]
You're welcome 😃
