### ISSUE TITLE
Using '?' as search shortcut in urls prevents from cache-busting in Chrome.

### ISSUE THREAD

**Issue by titos2k** [unsplash/unsplash-source-js#11]
Can someone please change the handling of search api via url into proper format like ?search=[phrase] instead of just ?[phrase], because of that reloading an image in Chrome is impossible because you can't cache-bust the image url with additional parameter like ?v=xyz. API interprets it as searched phrase instead of just ignore it.

**Comment by lukechesser** [comment]
Good catch @titos2k.

I'll chat with @aaronklaassen and see what we can do. We'll need to continue support for the previous way, but allow the new way to work too. Will get back to you

**Comment by aaronklaassen** [comment]
@titos2k You can use a `sig` param to bust the cache.

**Comment by titos2k** [comment]
thanks!
