### ISSUE TITLE
Wrong size returned

### ISSUE THREAD

**Issue by ogama8** [unsplash/unsplash-source-js#12]
[https://source.unsplash.com/random/3080x1920](url)
returns images like this.  Mis-scaled:  [https://images.unsplash.com/photo-1473643852383-a47c2b255eea?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1280&h=720&fit=crop&s=8206110aff646b24cffaab8ad0a052e5](url)

[https://source.unsplash.com/random](url) suffers from the same problem

**Comment by aaronklaassen** [comment]
Thanks @ogama8. I'm going to close this issue because it's a bug on the server-side, not this js wrapper, but we'll be on fixing it asap.
