### ISSUE TITLE
Small collections not randomizing

### ISSUE THREAD

**Issue by pschfr** [unsplash/unsplash-source-js#14]
#### Steps to Reproduce
Use [Unsplash Source](https://source.unsplash.com/) to load a small collection, for example, [this one with 6 photos](https://unsplash.com/collections/585985/the-burgh). You should get a random one of those six, but I only get [one](https://unsplash.com/collections/585985/the-burgh?photo=ae4KypxWHr8) of those images?

(I also made an issue on [Unsplash JS](https://github.com/unsplash/unsplash-js/issues/41), as I was unsure where to put this.)

**Comment by aaronklaassen** [comment]
@pschfr Do you have an example of how to reproduce this? Are you doing something like this (or equivalent):

```html
<img src="https://source.unsplash.com/collection/123/">
<img src="https://source.unsplash.com/collection/123/">
<img src="https://source.unsplash.com/collection/123/">
```

**Comment by pschfr** [comment]
Here's a CodePen with how I'm using it (as a background image):

https://codepen.io/pschfr/pen/MpOMoB

**Comment by aaronklaassen** [comment]
Hey @pschfr. I found the bug here. I'm actually going to close these issues because the problem is on the Unsplash API side (not in either of these wrappers - or even Source, for that matter). I'll file an issue with the rest of the dev team and we'll get it patched up.

**Comment by pschfr** [comment]
Good to hear! Thanks for your time 😄

**Comment by pschfr** [comment]
This ever get fixed? I don't mean to be a nag.

**Comment by pschfr** [comment]
Any word on a fix?

**Comment by pschfr** [comment]
Has this been patched? I kinda need this for a site I'm making...

**Comment by pschfr** [comment]
Anywhere I can track the status of this>

**Comment by aaronklaassen** [comment]
@pschfr Hey sorry for the delay getting back to you. We deployed a fix for this last week. Should be working just fine :+1:

**Comment by pschfr** [comment]
Awesome thanks! I can verify it works!
