### ISSUE TITLE
Add support for collections

### ISSUE THREAD

**Issue by Pczek** [unsplash/unsplash-source-js#6]
I really enjoy your source api, super easy to use!
Currently I'm using `categories` but I wish I could use `collections` instead. Categories feature way to much images and not all off them fit nicely together. Therefore, I would love to use curated collections like [Cabin Life](https://unsplash.com/collections/295/cabin-life) etc. .

**Comment by lukechesser** [comment]
@Pczek Great suggestion, we're definitely working on bringing that out :)

As soon as collections is supported by the JSON API (unsplash.com/documentation), then we'll update Unsplash Source to support it, and then update Unsplash Source JS to support that.

Collections support on the JSON API will be out in the next few weeks, as soon as collections is publicly available.
