### ISSUE TITLE
Multiple random images

### ISSUE THREAD

**Issue by Cam** [unsplash/unsplash-source-js#9]
I may just be missing something. But in it's most basic form, the API seems to just return the same image for any instance on a page where it is called more than once. Shouldn't each instance be seen as a different request by default?

**Comment by aaronklaassen** [comment]
@Cam This behaviour is actually your browser "helping" you. It sees the multiple requests to the same URL and caches the response - not knowing, of course, that in this case the response would actually be different each time.

The solution is something still missing from the Source docs (so thanks for the reminder to add it 😅): you have to force each URL to be unique. You can do that by adding a `sig` param to the query string. e.g. `https://source.unsplash.com/random?sig=123` It doesn't matter what the value is (it's ignored on the server-side), just that it's different for every instance on the page.

Does that make sense? You can email me at api@unsplash.com if you have any other questions.

**Comment by Cam** [comment]
Thanks @aaronklaassen. Yeah, that is what I thought was the situation.

I actually figured out my own way around it by appending a value onto the end of the URL using a loop to make it unique each time. So pretty much exactly what your suggestion was too 👍 

I started with a query string, but then found you could also just specify a number at the end of the URL and it would do essentially the same thing :)

`//source.unsplash.com/collection/1051/1`

**Comment by geordidearns** [comment]
Hey @aaronklaassen - I tried to add the sig=123 to the query string `https://source.unsplash.com/featured/?sig=123&iceland`
But it seems to return the same image each time in a for-loop (requesting 5 times) - it shows roughly two random images then duplicates - is there a cleaner more accurate way of returning 5 images related to a search query? :)

Thanks!

**Comment by hwanile** [comment]
I need to know the function that used to randomize images when refresh the page

**Comment by johnnyosullivan** [comment]
I just used this code to randomize the picture when you click on a button. Using the syntax that Aaron provided above and setting the number to the Math.random() function, I was able to randomize the picture upon each click. Perhaps, this will help somebody out there. 

**HTML**
<img id="image" src="https://source.unsplash.com/random" alt="unsplash">
<button id="imageButton">Image</button>

**jQuery**
$("#imageButton").click(function(){
  $("#image").attr("src", "https://source.unsplash.com/random?sig=" + Math.random())
});

**Comment by grig0ry** [comment]
Crop size not work with `https://source.unsplash.com/random?sig={{ random() }}/700x700`, returns images with different sizes.

**Comment by aaronklaassen** [comment]
@grig0ry That's not a valid query string; put the `/700x700` before the `?`.

**Comment by grig0ry** [comment]
@aaronklaassen OMG, I was inattentive, thx.

**Comment by DMCK96** [comment]
`for (int i = 0; i < 12; i++)
    {
        var sliderImage = "https://source.unsplash.com/100x67/apartment?sig=" + i;
    }`

Returns the same image on each loop.

**Comment by danistaki** [comment]
Hello everyone, back to the same topic. I am trying to refresh the random picture but keeps loading the same picture. I have been trying a lot of combination but no one has worked.
This is the original:
https://source.unsplash.com/1080x1920/?new&zealand
And I am trying to add the sig=325 (random numbers) to it but doesn't work. Where should I added to fix this cache stuff?
Thank you very much in advaced

**Comment by lukechesser** [comment]
@danistaki hmm, I can't reproduce, but the original params may be messing it up: spaces should be URL encoded as `%20` instead of `&`

**Comment by johnnyosullivan** [comment]
I was ultimately able to resolve this problem, but only after I signed up for a developer account with Unsplash, which was painless. I'll have to dig around for my code though.
